id: P732702D7
initial_creation_type: ocr
source_metadata:
  volumes:
    cbaab30a11b149afabb5b76f7c556353:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: དུས་གསུམ་བརྟག་པ།
      total_pages: 1198
      volume_number: 97
